name: Test

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24"

      - name: Run tests
        run: |
          go test -v ./...
